global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # KeyGrid HSM service
  - job_name: 'keygrid-hsm'
    static_configs:
      - targets: ['keygrid-hsm:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    
    # Relabeling rules
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: keygrid-hsm:8080
        
    # Metric relabeling
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'keygrid_hsm_.*'
        action: keep

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # PostgreSQL database metrics (if postgres_exporter is running)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    
  # Node metrics for container monitoring
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Alerting rules (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage settings
storage:
  tsdb:
    retention: 7d
    wal-compression: true